config/routes.rb
Rails.application.routes.draw do

  get 'reviews/show'

  get 'reviews/create'

  get 'reviews/destroy'

 root 'products#index'

 resources :users, only: [:new, :create]
 resources :sessions, only: [:new, :create, :destroy]
 resources :products do
  resources :reviews, only: [:show, :create, :destroy]
end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates :comment, :presence => true
end

app/models/user.rb
  class User < ActiveRecord::Base
  has_secure_password 
  has_many :reviews
  has_many :products, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
      else 
      Product.all
    end

    @products = @products.order('products.created_at DESC').page(params[:page])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @product = Product.find(params[:id])
  
    if current_user
      @review = @product.reviews.build
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  def update
  end

  def new
    @product = Product.new
  end
  def create
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user 
    
    respond_to do |format|
      if @review.save
        format.html {redirect_to product_path(@product.id), notice: 'Review added!'}
        format.js {}
      else 
        format.html { render 'products/show', alert: 'There was an error. Try again?'}
        format.js {}
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

private

  def review_params
   params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "You're signed in! YES!"
    else
      flash.now[:alert] = "Invalid email or password ): Try again?"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice=> "You've been logged out. See ya later!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Welcome to Rainforest, BITCH!"
    else
      render 'new', alert: "Something went wrong - try again?"
    end
  end


 private

 def user_params
  params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'></head>
<body>

<nav class="top-nav">

<h1 class="rainforest"> <%= link_to "RAINFOREST!", root_path %></h1>
  <ul>
    <li> <%= link_to "Home", root_path %></li>
    <li> <%= link_to "Products", products_path %> </li>
    <li> <%=link_to "+ New product", new_product_path %> </li>
  </ul>
</nav>

<div class="flash">
<% if flash[:notice] %>
<p id="notice"> <%= flash[:notice] %> </p>
<% end %>
<% if flash[:alert] %>
<p class="error-messages">  <%= flash[:alert] %> </p>
<% end %>
</div>

<%= yield %>
<footer>

<div class="user-info">
<% unless current_page?(controller:"sessions", action:"new") %>
 <% if current_user %>
  <p> You are signed in to Rainforest as <%= current_user.first_name %> <%= current_user.last_name %> </p>
  <p> <%= link_to "Click here to log out", session_path("current"), :method => :delete %></p>

 <% else %>

 <p> <%= link_to "Sign in to Rainforest", new_session_path %> or <%= link_to "Create an account", new_user_path %> </p>

 <% end %>
<%end%> 

 </footer>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <div class ="form">
    <div class="form-line">
    <%= f.label :name, :value => "Your product name:" %> 
    <%= f.text_field :name %>
    </div>   
    
    <div class="form-line">
    <%= f.label :price_in_cents, :value => "Your product price:" %>
    <%= f.text_field :price_in_cents %>
    </div>

    <div class="form-line">
    <div id="description-label"><%= f.label :description, :value => "Describe your product:" %> </div>
    <%= f.text_area :description %>
    </div>

    <div class="actions">
    <%= f.submit %>
    </div>

    

</div>
<% end %>

app/views/products/_product.html.erb
  <div class="product-container">

    <h2> <%= link_to product.name, "products/#{product.id}" %>, $<%= product.price_in_cents %></h1>

    <p> <%= product.description %> </p>

    <p><strong><%= link_to "EDIT", "products/#{product.id}/edit" %></strong></p>
  </div>

app/views/products/_review_form_errors.html.erb
   <% if @review.errors.present? %>
        <% @review.errors.full_messages.each do |error| %>
          <div class="alert">
            <%= error %>
          </div>
        <% end %>
    <% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <% if review.user != nil %>
  <div class="review">
    <div class="poster">
     
     <p> Posted by <%= review.user.first_name %> on <%= review.created_at %> </p>

    </div>
    <p class="comment">
      <%= review.comment %>
    </p>
  </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<div class ="width-container">
<p><%= link_to "<- Back to products", products_path %></p>

  <h1>Editing "<%= @product.name %>"</h1>

  <%= render "form" %>

</div>

app/views/products/index.html.erb
<div class="width-container">
  <h1>Products</h1>

  <p><small> <%= page_entries_info @products %></small></hp>

    <%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
    <% end %>
  
  <div id ="products">
    <%= render @products %>
  </div>


  <%= paginate @products %>
</div>

app/views/products/index.js.erb
<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
  <% else %>
  $('#products').append('<%= j render(@products) %>');
  <% end %>

  $('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<div class ="width-container">
<p> <%= link_to "<- Back to products page", products_url %></p>
  <h1> + Add a new product</h1>

 <%= render "form" %>

</div>

app/views/products/show.html.erb
<div class="width-container">
<p> <%= link_to "<- Back to products page", products_url %></p>

<div class="product-container">
<h1><%= @product.name %>, $<%= @product.price_in_cents %> </h1>
<p><strong><%= link_to "EDIT", "products/#{@product.id}/edit" %></strong></p>
<p> <%= @product.description %> </p>

</div>

<div id="review-list">
    <%= render :partial => "reviews" %>
</div>

<% if current_user %>
<h4> Add a review: </h4>

  <%= form_for [@product, @review], :remote => true do |f| %>
  
  <div id="review-form-errors">
    <%= render :partial => '/products/review_form_errors' %>
  </div>

    <div class ="field">

      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
     <%= f.submit %>
    </div>
  <% end %>
<% else %>

  <p> Please <%= link_to "log in", new_session_path %> to add a review </p>
  
<% end %>
</div>

<script type="text-javascript">
  $ function() {
    $("#new_review")
      .on('ajax:beforeSend', function() {
        $("input[type='submit']")
          .val('Saving...')
            .attr('disabled', 'disabled');
      })

      .on('ajax:complete', function (){
        $("input[type='submit']")
          .val('Create Review')
          .removeAttr('disabled');
      });
  });
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
  <div class="width-container">
  
  <h1>Create an account</h1>

  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class="error-messages">
    <h4> Your form didn't submit properly - this might be why: </h4>
    <ul>
      <% for message in @user.errors.full_messages %>
      <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form">
    <div class="form-line">
    <%= f.label :first_name %> <br />
    <%= f.text_field :first_name %>
    </div>

    <div class="form-line">
    <%= f.label :last_name %> <br />
    <%= f.text_field :last_name %>
    </div>

    <div class="form-line">
    <%= f.label :email %> <br />
    <%= f.text_field :email %>
    </div>
    
    <div class="form-line">
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
    </div>
    
    <div class="form-line">
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
    <%= f.submit %>
    </div>

    <% end %>

  </div>
</div>